# Generated by Django 3.0 on 2019-12-11 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the control (e.g. “Single-Qubit Driven Control”).', max_length=32)),
                ('type', models.CharField(choices=[('corpse', 'CORPSE'), ('gaussian', 'Gaussian'), ('cinbb', 'CinBB'), ('cinsk', 'CinSK')], max_length=8)),
                ('rabi_rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('polar_angle', models.DecimalField(decimal_places=10, default=0, max_digits=11, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
