# Generated by Django 3.0 on 2019-12-11 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
